server:
  port: 8888
spring:
  application:
    name: config-server
    logging:
      file: myapplication.log
  cloud:
    config:
      server:
        git:
          uri: toBeReplacedByRepositoryUrl 
          username: toBeReplacedByUserName
          password: toBeReplacedByUserPassword

